### ISSUE TITLE
Document template path

### ISSUE THREAD

**Issue by drozzy** [tsloughter/rebar3_erlydtl_plugin#12]
Looking at the erlang docs, one might get an idea that the templates should reside in the `templates` directory, right beside the `src` directory.

However, that is not so. Templates must be in the `priv/templates` directory (found this out after trial and error - and by looking at erlang source).

**Comment by tsloughter** [comment]
The erlang docs?

**Comment by tsloughter** [comment]
Oh, the docs generated from the code. Thanks, I'll update.

**Comment by drozzy** [comment]
Yeah, [there](https://github.com/tsloughter/rebar3_erlydtl_plugin/blob/master/src/rebar3_erlydtl_plugin.erl#L41)! 
And you already fixed it :-)

**Comment by drozzy** [comment]
Probably would be useful to add that detail to the `[README.md](https://github.com/tsloughter/rebar3_erlydtl_plugin/blob/master/README.md)` ;-)
